# Generated by Django 4.1 on 2022-10-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_auction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOOKS", "Books"),
                    ("CLOTH", "Clothes"),
                    ("ELECT", "Electronics"),
                    ("HEALTH", "Health"),
                    ("HOBBY", "Hobbies"),
                    ("KIDTO", "Toys"),
                    ("SPORT", "Sports"),
                    ("OTHER", "None"),
                ],
                default="None",
                max_length=100,
            ),
        ),
    ]
