# Generated by Django 4.1 on 2022-10-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="current_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BOOKS", "Books"),
                    ("CLOTH", "Clothes"),
                    ("ELECT", "Electronics"),
                    ("HEALTH", "Health"),
                    ("HOBBY", "Hobbies"),
                    ("KIDTO", "Toys"),
                    ("SPORT", "Sports"),
                    ("OTHER", "None"),
                ],
                default="OTHER",
                max_length=100,
            ),
        ),
    ]
