# Generated by Django 4.1 on 2022-10-02 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_watchlist_listing_alter_watchlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bid_price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bids",
            name="listing",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid",
                to="auctions.auction",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bids",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
