# Generated by Django 4.1 on 2022-10-02 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_bids_bid_price_bids_listing_bids_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Bids",),
        migrations.AddField(
            model_name="auction",
            name="bids",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="listing", to="auctions.bid"
            ),
        ),
    ]
