# Generated by Django 4.1 on 2022-10-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_rename_comment_comment_text_comment_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Clothes", "Clothes"),
                    ("Electronics", "Devices & Electronics"),
                    ("Health", "Health & Foods"),
                    ("Hobbies", "Hobbies"),
                    ("Toys", "Kids & Toys"),
                    ("Sports", "Sports"),
                    ("Tools", "Tools & Services"),
                    ("OTHER", "None"),
                ],
                default="OTHER",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="bid_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
